import type { Award } from '@/types/home'
import { AWARD_ROUTES } from './navigation'

/**
 * Static award configuration for SAA 2025.
 * All 6 awards share the same background image (award-bg.png).
 * Each has a unique name overlay image (award-name-{slug}.png).
 */
export const AWARDS: Award[] = [
  {
    id: 'top-talent',
    slug: 'top-talent',
    name: 'Top Talent',
    description: 'Giải thưởng Top Talent vinh danh những cá nhân xuất sắc toàn diện – những người không ngừng khẳng định năng lực chuyên môn vững vàng, hiệu suất công việc vượt trội, luôn mang lại giá trị vượt kỳ vọng, được đánh giá cao bởi khách hàng và đồng đội. Với tinh thần sẵn sàng nhận mọi nhiệm vụ tổ chức giao phó, họ luôn là nguồn cảm hứng, thúc đẩy động lực và tạo ảnh hưởng tích cực đến cả tập thể.',
    bgSrc: '/assets/home/images/award-bg.png',
    nameSrc: '/assets/home/images/award-name-top-talent.png',
    href: AWARD_ROUTES.topTalent,
    count: '10',
    countUnit: 'Cá nhân',
    value: '7.000.000 VNĐ',
    valueSuffix: 'cho mỗi giải thưởng',
  },
  {
    id: 'top-project',
    slug: 'top-project',
    name: 'Top Project',
    description: 'Vinh danh dự án tiêu biểu đạt hiệu quả cao nhất về kỹ thuật, kinh doanh và trải nghiệm khách hàng.',
    bgSrc: '/assets/home/images/award-bg.png',
    nameSrc: '/assets/home/images/award-name-top-project.png',
    href: AWARD_ROUTES.topProject,
    count: '02',
    countUnit: 'Tập thể',
    value: '15.000.000 VNĐ',
    valueSuffix: 'cho mỗi giải thưởng',
  },
  {
    id: 'top-project-leader',
    slug: 'top-project-leader',
    name: 'Top Project Leader',
    description: 'Vinh danh người dẫn dắt dự án xuất sắc, thể hiện năng lực lãnh đạo và quản lý hiệu quả.',
    bgSrc: '/assets/home/images/award-bg.png',
    nameSrc: '/assets/home/images/award-name-top-project-leader.png',
    href: AWARD_ROUTES.topProjectLeader,
    count: '03',
    countUnit: 'Cá nhân',
    value: '7.000.000 VNĐ',
    valueSuffix: 'cho mỗi giải thưởng',
  },
  {
    id: 'best-manager',
    slug: 'best-manager',
    name: 'Best Manager',
    description: 'Vinh danh quản lý truyền cảm hứng, xây dựng đội ngũ vững mạnh và thúc đẩy văn hóa tổ chức.',
    bgSrc: '/assets/home/images/award-bg.png',
    nameSrc: '/assets/home/images/award-name-best-manager.png',
    href: AWARD_ROUTES.bestManager,
    count: '01',
    countUnit: 'Cá nhân',
    value: '10.000.000 VNĐ',
    valueSuffix: 'cho mỗi giải thưởng',
  },
  {
    id: 'signature-2025-creator',
    slug: 'signature-2025-creator',
    name: 'Signature 2025 — Creator',
    description: 'Giải thưởng Signature vinh danh cá nhân hoặc tập thể thể hiện tinh thần đặc trưng mà Sun* hướng tới trong từng thời kỳ. Trong năm 2025, giải thưởng Signature vinh danh Creator - cá nhân/tập thể mang tư duy chủ động và nhạy bén, luôn nhìn thấy cơ hội trong thách thức và tiên phong trong hành động. Họ là những người nhạy bén với vấn đề, nhanh chóng nhận diện và đưa ra những giải pháp thực tiễn, mang lại giá trị rõ rệt cho dự án, khách hàng hoặc tổ chức. Với tư duy kiến tạo và tinh thần "Creator" đặc trưng của Sun*, họ không chỉ phản ứng tích cực trước sự thay đổi mà còn chủ động tạo ra cải tiến, góp phần định hình chuẩn mực mới cho cách mà người Sun* tạo giá trị.',
    bgSrc: '/assets/home/images/award-bg.png',
    nameSrc: '/assets/home/images/award-name-signature-creator.png',
    href: AWARD_ROUTES.signatureCreator,
    count: '01',
    countUnit: 'Cá nhân hoặc tập thể',
    value: '5.000.000 VNĐ',
    valueSuffix: 'cho giải cá nhân',
    value2: '8.000.000 VNĐ',
    valueSuffix2: 'cho giải tập thể',
  },
  {
    id: 'mvp',
    slug: 'mvp',
    name: 'MVP',
    description: 'Most Valuable Person — Vinh danh cá nhân có đóng góp giá trị lớn nhất cho Sun* trong năm qua.',
    bgSrc: '/assets/home/images/award-bg.png',
    nameSrc: '/assets/home/images/award-name-mvp.png',
    href: AWARD_ROUTES.mvp,
    count: '01',
    countUnit: 'Cá nhân',
    value: '15.000.000 VNĐ',
    valueSuffix: 'cho giải cá nhân',
  },
]
